import { storage } from "../storage";

export interface AiImageResult {
  url: string;
  credit: string;
  provider: string;
}

interface NovitaResponse {
  images?: Array<{
    image_url?: string;
    image_url_ttl?: number;
  }>;
  task_id?: string;
  status?: string;
  code?: number;
  msg?: string;
}

interface NovitaTaskResponse {
  task?: {
    status?: string;
    progress?: number;
  };
  images?: Array<{
    image_url?: string;
    image_url_ttl?: number;
  }>;
  code?: number;
  msg?: string;
}

export async function generateAiImage(
  prompt: string,
  model: string,
  novitaApiKey: string,
  campaignId?: number,
): Promise<AiImageResult | null> {
  if (!novitaApiKey) {
    throw new Error("Novita API key not configured");
  }

  try {
    const modelConfig = getModelConfig(model);
    
    const response = await fetch(modelConfig.endpoint, {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${novitaApiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model_name: modelConfig.modelName,
        prompt: prompt,
        negative_prompt: "blurry, low quality, distorted, deformed, ugly, bad anatomy, watermark, text, logo",
        width: 1024,
        height: 1024,
        steps: modelConfig.steps,
        guidance_scale: modelConfig.guidanceScale,
        seed: -1,
        sampler_name: "DPM++ 2M Karras",
        num_images: 1,
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Novita API error: ${response.status} - ${errorText}`);
    }

    const data: NovitaResponse = await response.json();

    if (data.code && data.code !== 0) {
      throw new Error(`Novita API error: ${data.msg || "Unknown error"}`);
    }

    if (data.task_id) {
      const imageUrl = await pollForResult(data.task_id, novitaApiKey);
      if (imageUrl) {
        if (campaignId) {
          await storage.createLog({
            campaignId,
            level: "info",
            message: `AI image generated successfully using ${model}`,
            metadata: { prompt: prompt.substring(0, 100), url: imageUrl },
          });
        }
        return {
          url: imageUrl,
          credit: `AI generated by Novita AI (${model})`,
          provider: "novita-ai",
        };
      }
    }

    if (data.images && data.images.length > 0 && data.images[0].image_url) {
      const imageUrl = data.images[0].image_url;
      if (campaignId) {
        await storage.createLog({
          campaignId,
          level: "info",
          message: `AI image generated successfully using ${model}`,
          metadata: { prompt: prompt.substring(0, 100), url: imageUrl },
        });
      }
      return {
        url: imageUrl,
        credit: `AI generated by Novita AI (${model})`,
        provider: "novita-ai",
      };
    }

    throw new Error("No image returned from Novita API");
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    console.error("AI image generation failed:", errorMessage);

    if (campaignId) {
      await storage.createLog({
        campaignId,
        level: "error",
        message: `AI image generation failed: ${errorMessage}`,
        metadata: { prompt: prompt.substring(0, 100), model },
      });
    }

    throw error;
  }
}

async function pollForResult(taskId: string, apiKey: string): Promise<string | null> {
  const maxAttempts = 60;
  const pollInterval = 2000;

  for (let i = 0; i < maxAttempts; i++) {
    await new Promise(resolve => setTimeout(resolve, pollInterval));

    const response = await fetch(`https://api.novita.ai/v3/async/task-result?task_id=${taskId}`, {
      headers: {
        "Authorization": `Bearer ${apiKey}`,
      },
    });

    if (!response.ok) {
      continue;
    }

    const data: NovitaTaskResponse = await response.json();

    if (data.task?.status === "TASK_STATUS_SUCCEED") {
      if (data.images && data.images.length > 0 && data.images[0].image_url) {
        return data.images[0].image_url;
      }
    } else if (data.task?.status === "TASK_STATUS_FAILED") {
      throw new Error("Image generation task failed");
    }
  }

  throw new Error("Image generation timed out");
}

function getModelConfig(model: string): {
  endpoint: string;
  modelName: string;
  steps: number;
  guidanceScale: number;
} {
  switch (model) {
    case "flux-1-schnell":
      return {
        endpoint: "https://api.novita.ai/v3/async/flux-schnell",
        modelName: "flux-schnell",
        steps: 4,
        guidanceScale: 0,
      };
    case "flux-1-dev":
      return {
        endpoint: "https://api.novita.ai/v3/async/flux-dev",
        modelName: "flux-dev",
        steps: 28,
        guidanceScale: 3.5,
      };
    case "sdxl":
      return {
        endpoint: "https://api.novita.ai/v3/async/txt2img",
        modelName: "sd_xl_base_1.0_0.9vae.safetensors",
        steps: 30,
        guidanceScale: 7.5,
      };
    case "sd-3":
      return {
        endpoint: "https://api.novita.ai/v3/async/sd3",
        modelName: "sd3",
        steps: 28,
        guidanceScale: 7,
      };
    default:
      return {
        endpoint: "https://api.novita.ai/v3/async/flux-schnell",
        modelName: "flux-schnell",
        steps: 4,
        guidanceScale: 0,
      };
  }
}

export function generateImagePrompt(caption: string, topic: string): string {
  const cleanCaption = caption
    .replace(/#\w+/g, "")
    .replace(/https?:\/\/\S+/g, "")
    .replace(/\n+/g, " ")
    .trim()
    .substring(0, 200);

  return `Professional social media image for ${topic}. ${cleanCaption}. High quality, vibrant colors, engaging composition, modern design, suitable for Instagram.`;
}
